# Jekyll configuration for Open SDG platform
baseurl: ""

remote_data_prefix: "https://odsvalencia.github.io/data/"
data_edit_url: http://prose.io/#ODSValencia/data/edit/develop/data/indicator_[id].csv
metadata_edit_url: http://prose.io/#ODSValencia/data/edit/develop/meta/[id].md
languages:
  - es
  - ca
  - en
  
# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@1.6.0

# Replace this title as needed.
title: general.site_title
url: ""
environment: staging


# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
  previous_next_links: true
create_goals:
  layout: goal-by-target-vertical
  previous_next_links: true
create_pages:
  pages:
    - folder: /
      layout: frontpage
    - folder: /goals
      layout: goals
    - folder: /reporting-status
      layout: reportingstatus
    - filename: indicators.json
      folder: /
      layout: indicator-json
    - folder: /search
      layout: search

country:
  name: Valencia
  adjective: Valencia
  
analytics:
  ga_prod: ''
  
frontpage_goals_grid:
  title: custom-translations.my-goals-grid-title
  description: Click on each goal for our Sustainable Development Goal global indicator data.

frontpage_cards:
  - title: frontpage.download_all
    include: components/download-all-data.html
  - title: Useful resources
    # Control the content of the card - can use Markdown.
    content: |
      [The Global Goals](https://estadisticavlc.shinyapps.io/Indicadores_ODS/)

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true
    
# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: general.goals
  - path: /reporting-status
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /faq
    translation_key: menu.faq
  - path: /management
    translation_key: custom-translations.management
    
footer_menu:
  - path: https://twitter.com/estadisticavlc
    translation_key: general.twitter
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
    
    
# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: custom-translations.local-metadata
metadata_tabs:
  - scope: national
    title: custom-translations.local-metadata
    description: custom-translations.description-local-metadata
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''
# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: https://open-sdg.org/sdg-translations/assets/img/goals

    
#map_options:
#  tileURL: https://{s}.tile.jawg.io/{id}/{z}/{x}/{y}{r}.png?access-token={accessToken}
#  tileOptions:
#    id: jawg-light
#    accessToken: lCtbMZiG4tbVWl7uq9EEch1yphnuLx9JyZL2qZwoQJ26wAu73oK1NkU4K50AALkp
#    attribution:  <a href="http://jawg.io" title="Tiles Courtesy of Jawg Maps" target="_blank">&copy; <b>Jawg</b>Maps</a> &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors | <a href="http://geoportal.statistics.gov.uk/">ONS</a>
#  minZoom: 4

#map_layers:
#  - min_zoom: 4
#    max_zoom: 6
#    staticBorders: true
#    subfolder: distritos
#    label: distrito
map_layers:
  -
    # This can be a local relative path or a remote URL.
    geojson_file: https://github.com/ODSValencia/data/Distritos.geojson
    # This is the property in the GeoJSON that holds the name of the region.
    name_property: nombre
    # This is the property in the GeoJSON that holds the "geocode" of the region.
    id_property: coddistrit
    # This controls the subfolder that the GeoJSON file will be created in.
    output_subfolder: Distritos
    # This adds a prefix to all the GeoJSON filenames.
    filename_prefix: indicator_
    
# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

# Specify any custom javascript files.
custom_js:
  - /assets/js/custom.js

# Specify the format of the language toggles. Choices are:
# "dropdown", "links", or "none"
header_language_toggle: dropdown
footer_language_toggle: none

# Configure the header style.
header:
  include: header-menu-left-aligned.html

# Specify whether the Series disaggregation should be a toggle (like units).
series_toggle: true

# Control the behavior of breadcrumbs for certain types of content.
breadcrumbs:
  post:
    - label: general.home
      path: /
    - label: menu.updates
      path: /news
  goal:
    - label: general.home
      path: /
    - label: general.goals
      path: /
  indicator:
    - label: general.home
      path: /
    - label: general.goals
      path: /

# Specify the style of header to use.
header:
  include: header-menu-left-aligned.html

# Use an accessible color-set for charts.
graph_color_set: accessible

accessible_tabs: true
accessible_charts: true
series_toggle: true

decimal_separator: ','
# Date format
date_formats:
  - type: standard
    language: en
    format: '%B %d, %Y'
  - type: standard
    language: es
    format: '%d de %B de %Y'
  - type: standard
    language: ca
    format: '%d de %B de %Y'
