# Jekyll configuration for Open SDG platform

remote_data_prefix: "https://odsvalencia.github.io/data/"
data_edit_url: http://prose.io/#ODSValencia/data/edit/develop/data/indicator_[id].csv
metadata_edit_url: http://prose.io/#ODSValencia/data/edit/develop/meta/[id].md
languages:
  - es
  - en
  
# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@1.6.0

# Replace this title as needed.
title: general.site_title
url: ""
environment: staging


# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
  previous_next_links: true
create_goals:
  layout: goal-by-target-vertical
  previous_next_links: true
create_pages:
  pages:
    - folder: /
      layout: frontpage
    - folder: /goals
      layout: goals
    - folder: /reporting-status
      layout: reportingstatus
    - filename: indicators.json
      folder: /
      layout: indicator-json
    - folder: /search
      layout: search

country:
  name: Valencia
  adjective: Valencia
  
frontpage_goals_grid:
  title: custom-translations.my-goals-grid-title
  description: Click on each goal for our Sustainable Development Goal global indicator data.


# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true
    
# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    translation_key: menu.inicio
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /faq
    translation_key: menu.faq
  - path: /guidance
    translation_key: menu.guidance
  - path: my-example-page/
    translation_key: My menu item

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE


decimal_separator: ','
# Date format
date_formats:
  - type: standard
    language: en
    format: '%B %d, %Y'
  - type: standard
    language: es
    format: '%d de %B de %Y'
  - type: standard
    language: ca
    format: '%d de %B de %Y'
