# Site settings
title: general.site_title
url: ""
data_dir: data
environment: staging

remote_data_prefix: "https://odsvalencia.github.io/data/"

# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
  previous_next_links: true
create_goals:
  layout: goal-by-target-vertical
  previous_next_links: true
create_pages:
  pages:
    - folder: /
      layout: frontpage
    - folder: /goals
      layout: goals
    - folder: /reporting-status
      layout: reportingstatus
    - filename: indicators.json
      folder: /
      layout: indicator-json
    - folder: /search
      layout: search

# Github Repo for Data
repo_name: data
branch: develop
org_name: ODSValencia

# Build settings
markdown: kramdown

decimal_separator: ','

# Date format
date_formats:
  - type: standard
    language: en
    format: '%B %d, %Y'
  - type: standard
    language: es
    format: '%d de %B de %Y'
  - type: standard
    language: ca
    format: '%d de %B de %Y'
    
# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

country:
  name: Valencia
  adjective: Valencia


# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# The list of languages that are translated. The first one is the default.
languages:
  - es
  - ca
  - en

# Goal image options
goal_image_base: https://open-sdg.org/sdg-translations/assets/img/goals

# Recommend accessibility improvements.
accessible_tabs: true
accessible_charts: true
graph_color_set: accessible

# Specify whether the Series disaggregation should be a toggle (like units).
series_toggle: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: general.goals
  - path: /reporting-status
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /faq
    translation_key: menu.faq
  - path: /management
    translation_key: custom-translations.management
    
footer_menu:
  - path: https://twitter.com/estadisticavlc
    translation_key: general.twitter
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@1.6.0

# Apply any custom Javascript.
custom_js:
  - /assets/js/custom.js

search_index_extra_fields:
  - indicator_available
  - graph_title
  - data_keywords
  
# Graphs
graph_color_set: accessible

hide_single_series: true
hide_single_unit: true
  
favicons: favicon.io 

#Mapping
#map_options:
#  tileURL: https://{s}.tile.jawg.io/{id}/{z}/{x}/{y}{r}.png?access-token={accessToken}
#  tileOptions:
#    id: jawg-light
#    accessToken: lCtbMZiG4tbVWl7uq9EEch1yphnuLx9JyZL2qZwoQJ26wAu73oK1NkU4K50AALkp
#    attribution:  <a href="http://jawg.io" title="Tiles Courtesy of Jawg Maps" target="_blank">&copy; <b>Jawg</b>Maps</a> &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors | <a href="http://geoportal.statistics.gov.uk/">ONS</a>
#  minZoom: 4

#map_layers:
#  - min_zoom: 4
#    max_zoom: 6
#    staticBorders: true
#    subfolder: distritos
#    label: distrito
map_layers:
  -
    # This can be a local relative path or a remote URL.
    geojson_file: https://github.com/ODSValencia/data/Distritos.geojson
    # This is the property in the GeoJSON that holds the name of the region.
    name_property: nombre
    # This is the property in the GeoJSON that holds the "geocode" of the region.
    id_property: coddistrit
    # This controls the subfolder that the GeoJSON file will be created in.
    output_subfolder: Distritos
    # This adds a prefix to all the GeoJSON filenames.
    filename_prefix: indicator_

frontpage_goals_grid:
  title: custom-translations.my-goals-grid-title
  description: Click on each goal for our Sustainable Development Goal global indicator data.

frontpage_cards:
  - title: frontpage.download_all
    include: components/download-all-data.html
   - title: Ampliación
    content: |
      [Información extra](https://www.valencia.es/cas/estadistica/inicio)  
   
