accessible_charts: true
accessible_tabs: true
analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
contrast_type: default
cookie_consent_form:
  enabled: false
country:
  name: custom-translations.ciudad
  adjective: custom-translations.ciudad
create_goals:
  layout: goal-by-target-vertical
  previous_next_links: false
  goals: []
create_indicators:
  layout: indicator
  previous_next_links: false
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: https://github.com/ODSValencia/data/tree/develop/data
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  phase: ''
  message: ''
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
favicons: favicon.io
footer_language_toggle: none
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  - path: 'https://twitter.com/estadisticavlc'
    translation_key: general.twitter
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Información
    content: |
      [Indicadore ODS Ayuntamiento de Valencia](https://estadisticavlc.shinyapps.io/Indicadores_ODS/)
frontpage_goals_grid:
  title: Datos de Valencia para los indicadores de los Objetivos de Desarrollo Sostenible
  description: >-
    Click on each goal for our Sustainable Development Goal global indicator
    data.
frontpage_heading: ''
frontpage_instructions: ''
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: goal.description
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header:
  include: header-menu-left-aligned.html
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: https://github.com/ODSValencia/data/tree/develop/meta/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: https://github.com/ODSValencia/data/tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: https://github.com/ODSValencia/data/tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
  exclude_fields: []
  translated: false
languages:
  - en
  - es
languages_public: []
logos: []
map_options:
  # Control the limits on zooming in/out in the map:
  minZoom: 5
  maxZoom: 10
  # If you would like to use tile (background) imagery, use these:
  # Control the choropleth color range. See https://gka.github.io/chroma.js/#chroma-brewer
  # 1 map color depending on goal --- start ---
  colorRange: ["#F6E8EC", "#E3BAC6", "#D18CA1", "#BE5E7B", "#AB3055", "#A21942", "#821435", "#610F28", "#410A1A", "#20050D"]
  # --- stop ---

  # Set the color for boundaries that have no data.
  noValueColor: '#f0f0f0'
  # For documentation on the style options below, see here:
  # https://leafletjs.com/reference-1.4.0.html#path-option
  # Set the default style for boundaries in the map:
  styleNormal:
    weight: 1
    opacity: 1
    color: '#888'
    fillOpacity: 0.7
  # Set the style for boundaries that have been selected/highlighted:
  styleHighlighted:
    weight: 1
    opacity: 1
    color: '#111'
    fillOpacity: 0.7
  # Set the style for top-level boundaries that are displaying in other layers.
  # Note: This is only applicable when using the "nested zoom" feature (see below).
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: 5,5
#map_layers:
#  - min_zoom: 4
#    max_zoom: 6
#    staticBorders: true
#    subfolder: distritos
#    label: distrito
map_layers:
  -
    # This can be a local relative path or a remote URL.
    geojson_file: https://github.com/ODSValencia/data/Distritos.geojson
    # This is the property in the GeoJSON that holds the name of the region.
    name_property: nombre
    # This is the property in the GeoJSON that holds the "geocode" of the region.
    id_property: coddistrit
    # This controls the subfolder that the GeoJSON file will be created in.
    #output_subfolder: Distritos
    # This adds a prefix to all the GeoJSON filenames.
    #filename_prefix: indicator_
        # The subfolder under 'geojson' in the data repository holding the GeoJSON files:
    subfolder: distritos
    # The label to use in the "Download GeoJSON" button:
    label: Distritos
    # The minimum zoom at which this layer should be visible.
    min_zoom: 0
    # The maximum zoom at which this layer should be visible.
    max_zoom: 20
    # Whether or not these boundaries should display statically on lower layers.
    staticBorders: true
menu:
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
  - path: /news
    translation_key: menu.updates
    dropdown: []
metadata_edit_url: https://github.com/ODSValencia/data/tree/develop/meta
metadata_tabs: []
news:
  category_links: false
non_global_metadata: indicator.national_metadata
progress_status:
  status_heading: ''
  status_types: []
remote_data_prefix: 'https://odsvalencia.github.io/data/'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
  status_types:
    - value: complete
      label: status.reported
      hide_on_goal_pages: false
    - value: inprogress
      label: status.statistics_in_progress
      hide_on_goal_pages: false
    - value: notstarted
      label: status.exploring_data_sources
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/ODSValencia/data'
repository_url_site: 'https://github.com/ODSValencia/site'
search_index_boost: []
search_index_extra_fields: []
series_toggle: true
sharethis_property: ''
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
